[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
RandLinearAlgebra = "da1d211a-c3bc-43b2-b5d0-ce83f16a0f3a"

[compat]
julia = "^1.11"
LinearAlgebra = "^1.12.0"
RandLinearAlgebra = "^0.2.4"
